import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Codemanager (with-electron)",
  description: "Generated by create electron app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="h-dvh overflow-y-auto">{children}</body>
    </html>
  );
}
